# Generated by Django 3.2.8 on 2021-12-16 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('identity', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('level', models.CharField(default='g', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('base_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('job', models.CharField(choices=[('r', 'receptionist'), ('m', 'manager')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.SmallIntegerField()),
                ('floor', models.SmallIntegerField()),
                ('available', models.CharField(choices=[('m', 'maintenance'), ('a', 'available'), ('b', 'booked')], default='a', max_length=1)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('price', models.IntegerField()),
                ('state', models.CharField(choices=[('p', 'in_progress'), ('c', 'canceled'), ('f', 'finished'), ('r', 'under_reservation')], default='p', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.customer')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.roomtype')),
            ],
        ),
    ]
