# Generated by Django 3.2.8 on 2021-12-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_guest_num',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
