# Generated by Django 3.2.8 on 2021-12-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0002_auto_20211216_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
