# Generated by Django 3.2.8 on 2021-12-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0003_roomtype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_card',
            field=models.IntegerField(default=0),
        ),
    ]
