# Generated by Django 3.2.8 on 2021-12-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0004_auto_20211222_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('p', 'in_progress'), ('c', 'canceled'), ('f', 'finished'), ('r', 'under_reservation'), ('i', 'checked_in')], default='p', max_length=1),
        ),
    ]
