# Generated by Django 3.2.8 on 2021-12-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0005_alter_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=2000)),
            ],
        ),
    ]
