# Generated by Django 3.2.8 on 2021-12-24 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0006_bankcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePriceManege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ratio', models.SmallIntegerField(default=1)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.roomtype')),
            ],
        ),
    ]
