# Generated by Django 3.2.8 on 2021-12-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0008_alter_basepricemanege_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
