# Generated by Django 3.2.8 on 2021-12-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0009_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tomato.resident'),
            preserve_default=False,
        ),
    ]
